name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3

    - name: 'Create env file'
      run: |
        echo 'SQL_SERVER_IP=${{secrets.SQL_SERVER_IP}}' >> .env.development
        echo 'SQL_SERVER_PORT=${{secrets.SQL_SERVER_PORT}}' >> .env.development
        echo 'SQL_USER=${{secrets.SQL_USER}}' >> .env.development
        echo 'SQL_DB=${{secrets.SQL_DB}}' >> .env.development
        echo 'APP_PORT=${{secrets.APP_PORT}}' >> .env.development

    - name: Build the Docker image
      run: docker build . --file Dockerfile_dev --tag walwalka/coinlistsbackend:dev
