name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3

    - name: 'Create env file'
      run: |
        echo 'SQL_SERVER_IP=${{secrets.SQL_SERVER_IP}}' >> .env.development
        echo 'SQL_SERVER_PORT=${{secrets.SQL_SERVER_PORT}}' >> .env.development
        echo 'SQL_USER=${{secrets.SQL_USER}}' >> .env.development
        echo 'SQL_DB=${{secrets.SQL_DB}}' >> .env.development
        echo 'SQL_PASS=${{secrets.SQL_PASS}}' >> .env.development
        echo 'APP_PORT=${{secrets.APP_PORT}}' >> .env.development
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: walwalka/coinlistsbackend
    
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile_dev
        push: true
        tags: dev

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile_dev --tag walwalka/coinlistsbackend:dev