name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3
    - name: 'Create env file'
      run: |
        touch .env
        echo "${{ secrets.SQL_SERVER_IP}}" > .env
        echo "${{ secrets.SQL_SERVER_PORT }}" > .env
        echo "${{ secrets.SQL_USER }}" > .env
        echo "${{ secrets.SQL_DB }}" > .env
        echo "${{ secrets.APP_PORT }}" > .env
    - name: Build the Docker image
      run: docker build . --file Dockerfile_dev --tag walwalka/coinlistsbackend:dev
