name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: prod-coins

    steps:
    - uses: actions/checkout@v3
    - name: 'Create env file'
      run: |
        echo 'SQL_SERVER_IP=${{secrets.PROD_SQL_SERVER_IP}}' >> .env.production
        echo 'SQL_SERVER_PORT=${{secrets.SQL_SERVER_PORT}}' >> .env.production
        echo 'SQL_USER=${{secrets.SQL_USER}}' >> .env.production
        echo 'SQL_DB=${{secrets.SQL_DB}}' >> .env.production
        echo 'SQL_PASS=${{secrets.SQL_PASS}}' >> .env.production
        echo 'APP_PORT=${{secrets.APP_PORT}}' >> .env.production
        
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
           
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: walwalka/coinlistsbackend:prod